
<h1> HALAMAN Web</h1>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    <p class="hal">INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB <br>
        INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB INI HALAMAN WEB </p>
    <hr>
    
    <div class="footer">
        <p>Fataa Kasyara</p>
    </div>